theme = "papercolor-dark"

[editor]
#color-modes = true
#line-number = "relative"
#mouse = false

# Resolve true color detection problems (e.g. on Linux in Windows WSL2)
# such as the error, "theme: theme requires true color support".
true-color = true

#[editor.indent-guides]
#render = true

#[editor.cursor-shape]
#insert = "bar"
#normal = "block"
#select = "underline"

#[keys.insert]
#esc = ["collapse_selection", "normal_mode"]

[keys.normal]
0 = "goto_line_start"

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[editor.statusline]
left = ["mode", "version-control", "file-name", "file-modification-indicator", "diagnostics"]
#center = []
right = ["spinner", "position-percentage", "position", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.file-picker]
hidden = false
#max-depth = 1

[editor.cursor-shape]
normal = "block"
insert = "underline"
select = "bar"

[editor.gutters.line-numbers]
min-width = 1

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
