#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

# COLORS
bspc config focused_border_color "#9556f5"
bspc config normal_border_color "#757575"

# FOCUS
#bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
#bspc config history_aware_focus           true

bspc rule -a Firefox desktop=^1
bspc rule -a Subl4 desktop=^2
bspc rule -a org.squidowl.halloy desktop=^4

dunst &
nitrogen --restore &
thonkbar &
mpdas &
#$HOME/.config/polybar/launch.sh
#xbindkeys
