SLEEP_TIME: 3
  :: /home/ryc/.scripts/sb-processor :: :: shell
 :: awk '{printf "%.1f", $1/1000}' /sys/class/thermal/thermal_zone6/temp :: :: shell
󱞟 :: free -h | awk 'NR==2{print $3}' | tr -d 'i' :: :: shell
󱊢 :: /home/ryc/.scripts/battery-noty :: :: shell
 :: date '+%a %d %b %Y   %I:%M %p' :: :: shell

