#!/usr/bin/env bash

# Dependencies:
# - lemonbar
# - feh
# - acpi
# - sed
# - pkill

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [[ -f '/tmp/leftwm-theme-down' ]]; then
    /tmp/leftwm-theme-down
    rm '/tmp/leftwm-theme-down'
fi
ln -s "$SCRIPTPATH/down" '/tmp/leftwm-theme-down'

# Set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# Set background
feh --bg-max "$SCRIPTPATH/background.png"

background_color='#1E1E28'
workspace_idx_modules=0

main_bar() {
  local pipe="/tmp/lemonbar-fifo"
  [[ -p "$pipe" ]] || mkfifo "$pipe"

  # LeftWM layout + modules
  leftwm-state -w "$workspace_idx_modules" \
   -t "$SCRIPTPATH/template.liquid" > "$pipe" &
  "$SCRIPTPATH/clock-module" > "$pipe" &
  "$SCRIPTPATH/battery-module" > "$pipe" &

  # Read and parse named pipe
  while read -r; do
      case "$REPLY" in
          C*) clock="${REPLY#?}" ;;
          B*) battery="${REPLY#?}" ;;
          *) wm="$REPLY" ;;
      esac

      printf '%s\n' "$wm%{r}| $battery | $clock |%{F-} "
  done < "$pipe" | lemonbar -p -g "$1" -B "$background_color" | sh
}

# Get workspace sizes
sizes=( $(leftwm-state -qn -t "$SCRIPTPATH/sizes.liquid" | sed -r '/^\s*$/d') )

idx=0
for size in "${sizes[@]}"; do
  if [[ "$idx" -eq "$workspace_idx_modules" ]]; then
    main_bar "$size" &
  else
    leftwm-state -w "$idx" -t "$SCRIPTPATH/template.liquid" | lemonbar -p \
     -g "$size" -B "$background_color" | sh &
  fi
  (( idx++ ))
done
