dunst &
nitrogen --restore &
#arbtt-capture &
#nicotine &
xsetroot -cursor_name left_ptr

#slstatus &
#yabar -c /home/rooyca/Documents/dotfiles/.config/yabar.config &
#picom &
#nohup a2ln &
#nohup python ~/.scripts/now_playing_spotify.py &
#xmobar &
#batsignal &

# KEYBINDS
xbindkeys

#conky | dwm-setstatus &
#statusbar.sh &
#mblocks &
#exec /usr/local/bin/dwm

#exec spectrwm
#exec awesome

#while :; do
#    dwm
#done
