#!/bin/sh
#
# cmus-notify with cover fallback
#
# Usage in cmus:
#   :set status_display_program=/path/to/cmus-notify
#

GENERIC_ICON="$HOME/.local/share/icons/cmus_generic.png"

notify()
{
    if [ -n "$3" ] && [ -f "$3" ]; then
        notify-send -a "cmus" -i "$3" "$1" "$2"
    else
        notify-send -a "cmus" -i "$GENERIC_ICON" "$1" "$2"
    fi
}

while test $# -ge 2
do
    eval _$1='$2'
    shift
    shift
done

cover=""

# Look for cover art in the track folder
if [ -n "$_file" ]; then
    dir=$(dirname "$_file")
    for img in "$dir"/{cover,folder,front}.{jpg,jpeg,png}; do
        [ -f "$img" ] && cover="$img" && break
    done
fi

if test -n "$_file"
then
    summary="$_artist"
    body="$_title\n$_album"

    notify "[$_status]" "$summary - $body" "$cover"

elif test -n "$_url"
then
    notify "[$_status]" "$_url\n$_title" "$cover"
else
    notify "cmus" "$_status" "$cover"
fi
