##### UI #####

# Status bar on top
set -g status-position top
set -g status-interval 2

# Colors & spacing
set -g status-bg colour237
set -g status-fg white
set -g status-left-length 30
set -g status-right-length 0

# Left = Session name
set -g status-left "#[bold] $:#S #[default]"

# Messages
set -g message-style bg=colour236,fg=white


##### KEYBINDS #####

# Unbind default prefix and set to Ctrl-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Ctrl-T -> new tab (window)
bind -n C-t new-window
bind v split-window -h   # vertical split
bind h split-window -v   # horizontal split

# Mouse support
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Pane navigation (no prefix)
bind -n C-h select-pane -L
bind -n C-l select-pane -R
bind -n C-j select-pane -D
bind -n C-k select-pane -U

# Resize panes (Alt + arrows)
bind -n M-Left resize-pane -L 3
bind -n M-Right resize-pane -R 3
bind -n M-Up resize-pane -U 3
bind -n M-Down resize-pane -D 3

# Switch tabs (Shift + arrows)
bind -n S-Left previous-window
bind -n S-Right next-window

# Kill pane or tab
bind -n C-x kill-pane
