#set -g status-position top
set -g mouse on

unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

setw -g mode-keys vi 
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard"

# 1-base indexing
set -g base-index 1
set -g pane-base-index 1


# --- Look & Feel ---
set -g default-terminal "${TERM}"
set -g terminal-overrides ",*:RGB"
# set -g status-bg "#695882"
# set -g status-fg "#FFFFFF"
set -g status-style bg=default,fg=white,bright
set -g status-left " "
set -g status-right "#[fg=white,bright] [#S]"

# Windows buttons
set -g window-status-format "●"
set -g window-status-current-format "●"

set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=magenta,nobold}"
set -g window-status-style 'fg=#4e4959,bg=default'
set -g window-status-bell-style "fg=red,nobold"

set -g renumber-windows on

